# 1) Build
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# 2) Serve (nginx)
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# SPA fallback (React Router / refresh)
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]